name: Conditional trigger for FE

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    paths:
      - 'frontend/**'
      
jobs:
  sonarqube_scan_fe:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Printing frontend file
        run: echo frontend/test.txt
      - name: Printing hello world
        run: echo "hello world"
