name: Conditional trigger

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
 
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
     types: [opened]
jobs:
  sonarqube_scan_be:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         depth: 0

      - name: Printing hello world
        run: echo "hello world"
