name: Testing Teams Notification
 
on:
  workflow_dispatch
  
jobs:
  notify:
    runs-on: ubuntu-latest    
    steps:      
    
    - name: Notification
      if: always()
      id: send_notification
      uses: rafal-slowik/gh-action-msteams@master
      with:
        webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

    - name: Send notification to Microsoft Teams 
      run: | 
       curl -s -X POST ${{ secrets.MS_TEAMS_WEBHOOK_URI }} -H 'Content-Type: application/json' -d '{ "text": "GitHub Actions: A new push has been made to the main branch." }' 
